apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "TestDocs"
  description: "This is a test docs"
  annotations:
    github.com/project-slug: padraigobrien/Testdocs
    backstage.io/techdocs-ref: url:https://github.com/padraigobrien/Testdocs
spec:
  type: documentation
  lifecycle: experimental
  owner: "padraigobrien"
